name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build for linux/amd64
        run: |
          GOOS=linux GOARCH=amd64 make VERSION=${{ github.ref_name }}
          mv ./output/bin/tagbag ./output/bin/tagbag-linux-amd64

      - name: Build for darwin/amd64
        run: |
          GOOS=darwin GOARCH=amd64 make VERSION=${{ github.ref_name }}
          mv ./output/bin/tagbag ./output/bin/tagbag-darwin-amd64

      - name: Build for darwin/arm64
        run: |
          GOOS=darwin GOARCH=arm64 make VERSION=${{ github.ref_name }}
          mv ./output/bin/tagbag ./output/bin/tagbag-darwin-arm64

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            output/bin/tagbag-*
